version: "3"
services:
  math:
    build: ./math_py
    
  string:
    build: ./string_rust
  
  random:
    build: ./random_js
  
  gateway:
    build: ./gateway
    ports:
      - 80:5000
    depends_on:
      - math
      - string
      - random